/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataReact: typeof import('./src/components/DataReact.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/views/test.vue')['default']
    TestChildMultiple: typeof import('./src/components/TestChildMultiple.vue')['default']
    TestChildSingle: typeof import('./src/components/TestChildSingle.vue')['default']
    VantPicker: typeof import('./src/components/VantPicker.vue')['default']
    Views: typeof import('./src/views/index.vue')['default']
  }
}
