/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    '测试子组件直接绑定事件': typeof import('./src/components/测试子组件直接绑定事件.vue')['default']
    App: typeof import('./src/App.vue')['default']
    'AutoImport.d': typeof import('./src/auto-import.d.ts')['default']
    DataReact: typeof import('./src/components/DataReact.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    Main: typeof import('./src/main.js')['default']
    Router: typeof import('./src/router/index.js')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Store: typeof import('./src/store/index.js')['default']
    Test: typeof import('./src/views/test.vue')['default']
    TestChild: typeof import('./src/components/TestChild.vue')['default']
    TestChildMultiple: typeof import('./src/components/TestChildMultiple.vue')['default']
    TestChildSingle: typeof import('./src/components/TestChildSingle.vue')['default']
    Views: typeof import('./src/views/index.vue')['default']
  }
}
