/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutoImport: typeof import('./src/views/autoImport.vue')['default']
    DataReact: typeof import('./src/components/DataReact.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    FlexVue: typeof import('./src/components/FlexVue.vue')['default']
    MoreText: typeof import('./src/components/MoreText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetUp: typeof import('./src/components/SetUp.vue')['default']
    SlideVue: typeof import('./src/components/SlideVue.vue')['default']
    SlotTest: typeof import('./src/components/SlotTest.vue')['default']
    Test: typeof import('./src/views/test.vue')['default']
    TestChildMultiple: typeof import('./src/components/TestChildMultiple.vue')['default']
    TestChildSingle: typeof import('./src/components/TestChildSingle.vue')['default']
    VanPicker: typeof import('vant/es')['Picker']
    VantPicker: typeof import('./src/components/VantPicker.vue')['default']
    Views: typeof import('./src/views/index.vue')['default']
  }
}
